#!/usr/bin/env bash
set -e

if [ $# -gt 0 ]
then
    if [ "$1" == "model" ]
    then
        [ -f "musicbrainz_django_models/models/$2.py" ] && echo "Already Exists" && exit
        _build/model.py $2
        vim "musicbrainz_django_models/models/$2.py" <`tty` >`tty`
        exit
    elif [ "$1" == "test" ]
    then
        _build/004-test
        exit
    elif [ "$1" == "docs" ]
    then
        _build/005-generate-docs "$2"
        exit
    fi
fi

run-parts --exit-on-error _build
