#!/usr/bin/env bash
set -e

if [ $# -gt 0 ]
then
    if [ "$1" == "model" ]
    then
        [ -f "musicbrainz_django_models/models/$2.py" ] && echo "Already Exists" && exit
        _build/model.py $2
        vim "musicbrainz_django_models/models/$2.py" <`tty` >`tty`
        exit
    elif [ "$1" == "test" ]
    then
        _build/004-test
        exit
    fi
fi

for build_script in $(ls -1 _build/0*)
do
    source $build_script "$*"
done
