#!/usr/bin/env bash
set -e

app='musicbrainz_django_models'
models="$app/models"
modules=$(ls -1 $app/models/*.py | grep -v __init__ | grep -v abstract__)

function PASSED() {
    echo -e "\e[1;32m PASSED\e[0m"
}
function OK() {
    echo -n '.'
}
function NOK() {
    echo -e "\e[1;31mFAILED\e[0m"
    exit 1
}

echo "================================================================================"
echo "                               Verifying Models                                 "
echo "================================================================================"
for module in $modules
do
    module_name=$(echo $module | cut -d '/' -f 3 | cut -d '.' -f 1)
    printf '%-64s' "Verifying: $module_name"

    grep 'from django.db import models' $module > /dev/null && OK || NOK

    grep 'from django.utils.encoding import python_2_unicode_compatible' $module > /dev/null && OK || NOK

    grep "^class $module_name" $module > /dev/null && OK || NOK

    grep "^class $module_name" $module -B 1 | head -1 | grep '@python_2_unicode_compatible' > /dev/null && OK || NOK

    rst_module=$(head -2 $models/$module_name.py | tail -1)
    [ "$rst_module" == ".. module:: $module_name" ] && OK || NOK

    grep "from .$module_name import $module_name" $app/models/__init__.py > /dev/null && OK || NOK

    grep "db_table = '$module_name'" $app/models/$module_name.py > /dev/null && OK || NOK

    # All Models must define __str__:
    grep '    def __str__(self):' $module > /dev/null && OK || NOK

    # All Models must NOT define __unicode__:
    grep '    def __unicode__(self):' $module > /dev/null && NOK || OK

    PASSED
done
