#!/usr/bin/env bash
set -e

app='musicbrainz_django_models'
models="$app/models"
tests="$app/tests"
admin="$app/admin"
modules=$(ls -1 $app/models/*.py | grep -v __init__)

function checking() {
    printf '  %-72s' "$1"
}
function OK() {
    echo -e "\e[1;32mPASSED\e[0m"
}
function NOK() {
    echo -e "\e[1;31mFAILED\e[0m"
    exit 1
}

echo "================================================================================"
echo "                                  Remodelling                                   "
echo "================================================================================"
[ -f "db.sqlite3" ] && rm "db.sqlite3"
rm -rf "$app/migrations/*"
rm -rf "$models/__pycache__"
rm -rf "$app/tests/__pycache__"
rm -rf "$app/__pycache__"
./manage.py makemigrations $app
./manage.py migrate
./manage.py loaddata musicbrainz_django_models/fixtures/*
