#!/usr/bin/env bash
set -e

app='musicbrainz_django_models'
models="$app/models"
tests="$app/tests"

echo "================================================================================"
echo "                                  Remodelling                                   "
echo "================================================================================"
[ -f "db.sqlite3" ] && rm "db.sqlite3"
rm -rf $app/migrations/*
rm -rf "$models/__pycache__"
rm -rf "$app/tests/__pycache__"
rm -rf "$app/__pycache__"
echo 'Making Migations' && ./manage.py makemigrations $app
echo 'Mirgating'        && ./manage.py migrate
echo 'Loading Fixtures' && ./manage.py loaddata musicbrainz_django_models/fixtures/*
